camel:
  service:
    lra:
      enabled: true
      coordinator-url: http://lra-coordinator.saga.svc:8080
      local-participant-url: http://camel-saga-payment-service.saga.svc:8080/api
  component:
    servlet:
      mapping:
        context-path: /api/*

